YJ_003: Create Project Endpoint
The-Yammer-Jammers/soniak-bew-draziwpord-avaj pull request #7
Opened 2024-11-07 15:18 UTC by dylanBkainos

👍

2024-11-07 15:50 UTC, lukemKainos requested changes

2024-11-07 15:50 UTC, lukemKainos commented on src/main/java/org/example/daos/ProjectDao.java
> +        Connection connection = DatabaseConnector.getConnection();
try around this connection pls

2024-11-07 15:50 UTC, lukemKainos commented on src/main/java/org/example/daos/ProjectDao.java
> +        Connection c = DatabaseConnector.getConnection();
surround with a try

2024-11-07 15:50 UTC, lukemKainos commented on src/main/java/org/example/daos/ProjectDao.java
> +        final int fifthValue = 5;
please dont just say values, instead do what they are

2024-11-07 15:50 UTC, lukemKainos commented on src/main/java/org/example/daos/ProjectDao.java
> +                        resultSet.getBoolean("completed"));
this code is duplicated

2024-11-07 15:50 UTC, lukemKainos commented on src/main/java/org/example/exceptions/DoesNotExistException.java
> +public class DoesNotExistException extends Throwable {
Extend exception

2024-11-07 15:50 UTC, lukemKainos commented on src/main/java/org/example/mappers/ProjectMapper.java
> +                .collect(Collectors.toList());
return projects.stream()
                .map(ProjectMapper::mapToProjectResponse)
                .collect(Collectors.toList());

2024-11-07 15:50 UTC, lukemKainos commented on src/main/java/org/example/models/Project.java
> +    private boolean completed;
should be isCompleted

2024-11-07 17:00 UTC, Aaron-Millen approved these changes

2024-11-08 09:49 UTC, Aaron-Millen approved these changes

2024-11-08 09:52 UTC, lukemKainos approved these changes

2024-11-08 09:57 UTC, lukemKainos approved these changes

2024-11-08 09:57 UTC, merged